# Generated by Django 3.1.2 on 2020-10-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='temp',
            field=models.FloatField(),
        ),
    ]
