# Generated by Django 3.1.2 on 2020-10-05 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracer', '0002_auto_20201005_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
